apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: myns
spec:
  containers:
  - name: test
    image: python
    command:
    - python3
    - -c
    - "import os;print(os.environ['PASSWORD'])"
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: mypass
